version: '3'

services:
  selfbalancingbot:
    image: gabs28/selfbalancingbot:latest
    container_name: selfbalancingbot
    privileged: true
    restart: always
    cap_add:
      - CAP_SYS_TTY_CONFIG
      - SYS_RAWIO
    volumes:
      - /dev:/dev
      - /tmp:/tmp
    devices:
      - "/dev/mem:/dev/mem"
    stdin_open: true
    tty: true

  face:
    image: torizonextras/torizon-robo-demo-arm64-vivante
    container_name: slint-face
    restart: always
    volumes:
      - /dev:/dev
      - /tmp:/tmp
      - /run/udev/:/run/udev/
    device_cgroup_rules:
      - 'c 4:* rmw'
      - 'c 13:* rmw'
      - 'c 199:* rmw'
      - 'c 226:* rmw'
    depends_on:
      - weston

  weston:
    image: torizon/weston-vivante:3
    environment:
      - ACCEPT_FSL_EULA=1
    # Required to get udev events from host udevd via netlink
    network_mode: host
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: /run/udev
        target: /run/udev
    cap_add:
      - CAP_SYS_TTY_CONFIG
    device_cgroup_rules:
      - "c 4:0 rmw"
      - "c 4:1 rmw"
      - "c 4:7 rmw"
      - "c 13:* rmw"
      - "c 199:* rmw"
      - "c 226:* rmw"
